### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mmyers1** [zhyu-lab/rccae#1]
I am running the following compilation error when trying to compile rccae on Red Hat Linux 8, using gcc version 14.1.0:

```
[  2%] Built target split
[  5%] Built target fastahack
[ 50%] Built target kent
[ 85%] Built target bamtools
[ 88%] Built target config
[ 89%] Building CXX object lib/CMakeFiles/genomedata.dir/genomedata/GenomeData.cpp.o
In file included from /data1/shahs3/users/myersm2/repos/rccae/prep/lib/genomedata/GenomeData.cpp:28:
/data1/shahs3/users/myersm2/repos/rccae/prep/lib/kent/inc/bbiFile.h:316:8: error: template argument required for ‘struct hash’
 struct hash *bbiChromSizesFromFile(char *fileName);
        ^~~~
/data1/shahs3/users/myersm2/repos/rccae/prep/lib/kent/inc/bbiFile.h:329:9: error: template argument required for ‘struct hash’
  struct hash *chromSizesHash, int *retMinDiff, double *retAveSize, bits64 *retBedCount);
         ^~~~
make[2]: *** [lib/CMakeFiles/genomedata.dir/build.make:76: lib/CMakeFiles/genomedata.dir/genomedata/GenomeData.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:331: lib/CMakeFiles/genomedata.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by zhyu-lab** [comment]
Thank you. We have fixed the bug.

**Comment by zhaoxiaofei** [comment]
I got the same compiling error. I am wondering how this issue can be fixed?

(rccae) zhaoxiaofei@DESKTOP-FG14CCH:/mnt/e/cnv/cnvguider/data3to4code/rccae/prep$ make
[  2%] Built target split
[  5%] Built target fastahack
[ 50%] Built target kent
[ 85%] Built target bamtools
[ 88%] Built target config
[ 89%] Building CXX object lib/CMakeFiles/genomedata.dir/genomedata/GenomeData.cpp.o
In file included from /mnt/e/cnv/cnvguider/data3to4code/rccae/prep/lib/genomedata/GenomeData.cpp:28:
/mnt/e/cnv/cnvguider/data3to4code/rccae/prep/lib/kent/inc/bbiFile.h:316:8: error: template argument required for ‘struct hash’
  316 | struct hash *bbiChromSizesFromFile(char *fileName);
      |        ^~~~
/mnt/e/cnv/cnvguider/data3to4code/rccae/prep/lib/kent/inc/bbiFile.h:329:16: error: template argument required for ‘struct hash’
  329 |         struct hash *chromSizesHash, int *retMinDiff, double *retAveSize, bits64 *retBedCount);
      |                ^~~~
make[2]: *** [lib/CMakeFiles/genomedata.dir/build.make:79: lib/CMakeFiles/genomedata.dir/genomedata/GenomeData.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:387: lib/CMakeFiles/genomedata.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
